site_name: FastAPI Databases
nav:
  - Getting Started: index.md
  - Install: install.md
  - Full Example: example.md
theme:
  name: "material"
  palette:
    primary: "green"
markdown_extensions:
  - codehilite
